### ISSUE TITLE
should this repository be removed in favor of the 'governance' repo?

### ISSUE THREAD

**Issue by erikerlandson** [Enterprise-Neurosystem/Main#4]
The `governance` repo (https://github.com/Enterprise-Neurosystem/governance) seems to be subsuming the functionality of this repository.  Should we consider removing it?

cc @lcaywood2  @bwright-aiml @adrezni

**Comment by adrezni** [comment]
agree we  should remove it :)

**Comment by erikerlandson** [comment]
I do not have org privileges to remove it. Unsure who else does besides @bwright-aiml
